// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NonProfitDB.Models;

public partial class NonProfitDBContext : DbContext
{
    public NonProfitDBContext(DbContextOptions<NonProfitDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BankAccount> BankAccounts { get; set; }

    public virtual DbSet<Donation> Donations { get; set; }

    public virtual DbSet<DonationCategory> DonationCategories { get; set; }

    public virtual DbSet<Donor> Donors { get; set; }

    public virtual DbSet<Expense> Expenses { get; set; }

    public virtual DbSet<ExpenseCategory> ExpenseCategories { get; set; }

    public virtual DbSet<TransactionLedger> TransactionLedgers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BankAccount>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__BankAcco__349DA5A6BA310646");

            entity.ToTable("BankAccount");

            entity.Property(e => e.AccountName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CurrentBalance)
                .HasDefaultValue(0.0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__BankAccou__Curre__33D4B598");
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__BankAccou__LastU__34C8D9D1");
        });

        modelBuilder.Entity<Donation>(entity =>
        {
            entity.HasKey(e => e.DonationId).HasName("PK__Donation__C5082EFB6E94C657");

            entity.ToTable("Donation");

            entity.Property(e => e.EntryDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Donation__EntryD__29572725");
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.PaymentMethod).HasMaxLength(50);
            entity.Property(e => e.RecordedBy).HasMaxLength(100);
            entity.Property(e => e.ReferenceNumber).HasMaxLength(100);

            entity.HasOne(d => d.DonationCategory).WithMany(p => p.Donations)
                .HasForeignKey(d => d.DonationCategoryId)
                .HasConstraintName("FK__Donation__Donati__2B3F6F97");

            entity.HasOne(d => d.Donor).WithMany(p => p.Donations)
                .HasForeignKey(d => d.DonorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Donation__DonorI__2A4B4B5E");
        });

        modelBuilder.Entity<DonationCategory>(entity =>
        {
            entity.HasKey(e => e.DonationCategoryId).HasName("PK__Donation__4EA6D65E267D6F5F");

            entity.ToTable("DonationCategory");

            entity.Property(e => e.DonationCategoryId).ValueGeneratedNever();
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Description).HasMaxLength(255);
        });

        modelBuilder.Entity<Donor>(entity =>
        {
            entity.HasKey(e => e.DonorId).HasName("PK__Donor__052E3F782CF6ABC4");

            entity.ToTable("Donor");

            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.State).HasMaxLength(50);
            entity.Property(e => e.ZipCode).HasMaxLength(20);
        });

        modelBuilder.Entity<Expense>(entity =>
        {
            entity.HasKey(e => e.ExpenseId).HasName("PK__Expense__1445CFD383D144D2");

            entity.ToTable("Expense");

            entity.Property(e => e.EntryDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Expense__EntryDa__300424B4");
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.Payee).HasMaxLength(255);
            entity.Property(e => e.PaymentMethod).HasMaxLength(50);
            entity.Property(e => e.RecordedBy).HasMaxLength(100);
            entity.Property(e => e.ReferenceNumber).HasMaxLength(100);

            entity.HasOne(d => d.ExpenseCategory).WithMany(p => p.Expenses)
                .HasForeignKey(d => d.ExpenseCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Expense__Expense__30F848ED");
        });

        modelBuilder.Entity<ExpenseCategory>(entity =>
        {
            entity.HasKey(e => e.ExpenseCategoryId).HasName("PK__ExpenseC__9C2C63F810453D95");

            entity.ToTable("ExpenseCategory");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Description).HasMaxLength(255);
        });

        modelBuilder.Entity<TransactionLedger>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__Transact__55433A6B45E7101E");

            entity.ToTable("TransactionLedger");

            entity.Property(e => e.EntryDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Transacti__Entry__38996AB5");
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.TransactionType).HasMaxLength(20);

            entity.HasOne(d => d.Account).WithMany(p => p.TransactionLedgers)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__Transacti__Accou__398D8EEE");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}